### ISSUE TITLE
重新设计

### ISSUE THREAD

**Issue by happypeter** [happypeter/b-haoqicat#1]
对 http://b.haoqicat.com 进行改版

要求：

- 先出 sketch 图
- https://desktop.github.com/ 参考这里，主色用黑色，强调色用 #00bcd4

页面内容：

- 除了页面已有内容
- 还要添加工作室项目案例

**Comment by happypeter** [comment]
![image](https://user-images.githubusercontent.com/72467/30044266-bea45f48-922e-11e7-8798-7d39b9c8ed4d.png)

咱们的图标也设计成这个风格的，用 sketch 画。

**Comment by happypeter** [comment]
参考：

- http://personx-html.coderpixel.com/
- https://facebook.github.io/yoga/

**Comment by happypeter** [comment]
尽量发挥你自己的能力，其实我的要求就是：

- 好看
- 凸显出 00bcd4 

其他的你都可以自由发挥。

**Comment by chunyuezhang** [comment]
B站设计排期

1. 学完社交网站视频课程 4h
2. logo 1h
3. 整体设计 2h
4. 参考优秀网站  4h
5. 文案 1h 
6. 动效 2h
7. 出sketch 设计图 12h

**Comment by chunyuezhang** [comment]
logo-sketch  https://coding.net/s/1c6a313e-01ed-4ddb-bbb2-b074a12f437b

**Comment by happypeter** [comment]
效果很棒！

**Comment by chunyuezhang** [comment]
第一版设计图-sketch https://coding.net/s/150a0191-d84e-4c7a-af99-e0ed6ba67234

-png  
1.  https://coding.net/s/b0c241ed-2e80-4820-ab68-edcd8516e5f7
2. 鼠标hover效果图 https://coding.net/s/fd0013bb-61e0-43d2-8806-454908dd72ce

**Comment by happypeter** [comment]
支持平台：

- 电脑 chrome 端
- 手机 andriod 微信，和 ios 微信

**Comment by happypeter** [comment]
联系方式，把电话去掉。把我的头像添加上，写上这样的话：

>您可以直接联系 Peter 。

然后把我的微信，放在旁边，作为首选联络方式。

**Comment by chunyuezhang** [comment]
好的

**Comment by happypeter** [comment]
@chunyuezhang 方便时请把代码上传一下。
