### ISSUE TITLE
实现新版

### ISSUE THREAD

**Issue by happypeter** [happypeter/b-haoqicat#3]
https://coding.net/u/happypeter/p/haoqi-lab/attachment/default/preview/2784666

使用 create-react-app 把上面的设计图，实现成 react 页面。

**Comment by happypeter** [comment]
@youngjingwen  目前这是你的唯一一个项目，看到后下面回复一下。

同时每天在下面留一下言，跟大家汇报一下进度。每天进度多少都没有关系，但是一定要简单留言一下，谢谢。

**Comment by youngjingwen** [comment]
@happypeter 好的

**Comment by youngjingwen** [comment]
更新了 sketch ，使用 create-react-app 进行搭建工作

**Comment by happypeter** [comment]
👍

**Comment by youngjingwen** [comment]
完成了页面重构

**Comment by happypeter** [comment]
Great! 那就把代码直接 push 到本仓库的 master 分支吧。我先看一下，然后在考虑部署问题。

**Comment by youngjingwen** [comment]
昨天更新共享教育小程序的代码忘记上传了，现已上传

**Comment by happypeter** [comment]
好，我看一下

**Comment by happypeter** [comment]
嗯，这个 没有问题了。
