### ISSUE TITLE
实现 v5 设计

### ISSUE THREAD

**Issue by happypeter** [happypeter/b-haoqicat#5]
- v5: 2017.11.28
  - 只是修改了《好奇猫工作室》
  - 把《好奇猫》《好奇猫工作室》《好奇猫流程图》分别放到了不同的 Page
  - 添加《好奇猫工作室》的响应式
  - 对《工作室》的 Hero 部分添加了背景图，并修改了文字
  - 调整了《工作室》的《work》这部分的图片尺寸

https://coding.net/u/happypeter/p/haoqi-lab/attachment/default/preview/2882763

**Comment by happypeter** [comment]
另外，静文有空上传一下 github 头像。

**Comment by youngjingwen** [comment]
好的

**Comment by youngjingwen** [comment]
@happypeter 老师，`把《好奇猫》《好奇猫工作室》《好奇猫流程图》分别放到了不同的 Page` 这个我没理解

**Comment by happypeter** [comment]
哦，这个指的是 sketch 软件内部的 page
<img width="295" alt="2017-11-29 7 23 04" src="https://user-images.githubusercontent.com/72467/33372965-758000d6-d4c5-11e7-8a37-4759bf3b48ee.png">

**Comment by happypeter** [comment]
静文，你只要关心上面的 `好奇猫工作室` 下的内容即可。

**Comment by youngjingwen** [comment]
明白了老师

**Comment by youngjingwen** [comment]
@happypeter 老师 ，代码上传了

**Comment by happypeter** [comment]
cool

**Comment by happypeter** [comment]
这里的任务都完成了。
